SPORTS = {
    "boxing": {"name":"Бокс","emoji":"🥊","tags":{"speed":5,"reaction":5,"strength":4,"endurance":4,"coordination":5,"flexibility":2,"balance":4,"contact":5,"competition":5,"individual":5,"team":1,"precision":2,"rhythm":3,"jumping":2,"outdoor":2}},
    "wrestling": {"name":"Вольная борьба","emoji":"🤼","tags":{"speed":4,"reaction":5,"strength":5,"endurance":4,"coordination":5,"flexibility":4,"balance":5,"contact":5,"competition":5,"individual":5,"team":1,"precision":1,"rhythm":2,"jumping":2,"outdoor":2}},
    "judo": {"name":"Дзюдо","emoji":"🥋","tags":{"speed":4,"reaction":5,"strength":4,"endurance":3,"coordination":5,"flexibility":4,"balance":5,"contact":5,"competition":5,"individual":5,"team":1,"precision":3,"rhythm":2,"jumping":1,"outdoor":1}},
    "sambo": {"name":"Самбо","emoji":"🥋","tags":{"speed":4,"reaction":5,"strength":5,"endurance":4,"coordination":5,"flexibility":4,"balance":5,"contact":5,"competition":5,"individual":5,"team":1,"precision":2,"rhythm":2,"jumping":1,"outdoor":1}},
    "mma": {"name":"ММА","emoji":"🥊","tags":{"speed":5,"reaction":5,"strength":5,"endurance":5,"coordination":5,"flexibility":4,"balance":4,"contact":5,"competition":5,"individual":5,"team":1,"precision":2,"rhythm":3,"jumping":2,"outdoor":1}},
    "archery": {"name":"Стрельба из лука","emoji":"🏹","tags":{"speed":1,"reaction":2,"strength":3,"endurance":2,"coordination":4,"flexibility":3,"balance":4,"contact":1,"competition":4,"individual":5,"team":2,"precision":5,"rhythm":2,"jumping":1,"outdoor":4}},
    "acrobatics": {"name":"Спортивная акробатика","emoji":"🤸","tags":{"speed":3,"reaction":4,"strength":4,"endurance":3,"coordination":5,"flexibility":5,"balance":5,"contact":2,"competition":4,"individual":3,"team":4,"precision":4,"rhythm":5,"jumping":5,"outdoor":1}},
    "trampoline": {"name":"Прыжки на батуте","emoji":"🤸","tags":{"speed":3,"reaction":5,"strength":4,"endurance":3,"coordination":5,"flexibility":4,"balance":5,"contact":1,"competition":4,"individual":5,"team":1,"precision":4,"rhythm":4,"jumping":5,"outdoor":1}},
    "weightlifting": {"name":"Тяжёлая атлетика","emoji":"🏋️","tags":{"speed":3,"reaction":3,"strength":5,"endurance":2,"coordination":5,"flexibility":4,"balance":4,"contact":1,"competition":5,"individual":5,"team":1,"precision":4,"rhythm":2,"jumping":2,"outdoor":1}},
    "athletics": {"name":"Лёгкая атлетика","emoji":"🏃","tags":{"speed":5,"reaction":4,"strength":4,"endurance":5,"coordination":4,"flexibility":3,"balance":4,"contact":1,"competition":5,"individual":5,"team":2,"precision":3,"rhythm":3,"jumping":4,"outdoor":5}}
}
